name: 'NPM Authentication'
description: 'Set username/password authentication credentials for NPM.'

inputs:
  registry:
    description: 'NPM registry'
    required: true

  username:
    description: 'NPM username'
    required: true

  password:
    description: 'NPM password'
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        AUTH_STRING=`echo -n "${{ inputs.username }}:${{ inputs.password }}" | base64`
        echo "registry=${{ inputs.registry }}:always-auth=true:_auth=${AUTH_STRING}" >> ~/.npmrc
      shell: bash